# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20161018_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время создания отзыва'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время выбора вина'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='has_answered',
            field=models.BooleanField(default=False, verbose_name='Пользователь оставил отзыв'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='has_declined',
            field=models.BooleanField(default=False, verbose_name='Пользователь отказался осталвть отзыв'),
        ),
    ]
