# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0003_favorites_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set([('user', 'wine')]),
        ),
    ]
