# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_country_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название страны'),
        ),
        migrations.AlterField(
            model_name='country',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='короткое название страны'),
        ),
    ]
