# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20161019_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Оценка от пользователя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='gender',
            field=models.NullBooleanField(default=None, verbose_name='Пол юзера'),
        ),
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.CharField(max_length=250, verbose_name='Нода для графа'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='alcohol',
            field=models.CharField(max_length=255, null=True, verbose_name='Процент алкоголя'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='food',
            field=models.CharField(max_length=2000, verbose_name='Сочетающаяся еда'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='stylistic',
            field=models.CharField(max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Сладость'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Год производства'),
        ),
    ]
