# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20161020_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='wine',
            unique_together=set([]),
        ),
    ]
