# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20161021_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='Для выбора метода-парсера в краулере')),
                ('name', models.CharField(max_length=255, verbose_name='Название магазина')),
                ('photo', models.ImageField(upload_to='img/')),
                ('search_url', models.CharField(max_length=255, verbose_name='Урл для поиска')),
                ('answer_type', models.CharField(choices=[('json', 'json'), ('html', 'html')], max_length=10, verbose_name='Тип ответа (json/html)')),
                ('base_url', models.CharField(max_length=255, verbose_name='Базовый урл')),
            ],
        ),
        migrations.CreateModel(
            name='WineToShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('url', models.CharField(max_length=255, verbose_name='Ссылка на товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.WineShop')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Wine')),
            ],
        ),
    ]
