# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 09:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_wineshop_winetoshop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='wine',
            options={'verbose_name': 'Вино', 'verbose_name_plural': 'Вина'},
        ),
        migrations.AlterModelOptions(
            name='wineshop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазин'},
        ),
        migrations.AlterModelOptions(
            name='winetoshop',
            options={'verbose_name': 'Вино в магазине', 'verbose_name_plural': 'Вина в магазине'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=100, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='api_response',
            field=models.IntegerField(default=0, verbose_name='Ответ РС'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Wine', verbose_name='Вино'),
        ),
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(default='korica.jpg', upload_to='img/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='color',
            field=models.CharField(max_length=10, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Картинка вина'),
        ),
        migrations.AlterField(
            model_name='winetoshop',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='winetoshop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.WineShop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='winetoshop',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Wine', verbose_name='Вино'),
        ),
    ]
