# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 00:27
from __future__ import unicode_literals
from survey.models import Wine
from django.db import migrations

def average_price(apps, schema_editor):
    wines = Wine.objects.all()
    for w in wines:
        shops =[s.price for s in w.get_shops()]
        if len(shops) != 0:
            average_price = round(sum(shops)/len(shops), 1)
            w.price = average_price
            w.save()

class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20161110_0917'),
    ]

    operations = [
        migrations.RunPython(average_price),
    ]
