# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-26 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_auto_20161114_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='translit_title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Название транслитом'),
        ),
    ]
