# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-27 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20161127_1508'),
        ('survey', '0016_auto_20161127_1720'),
    ]

    operations = [
    ]
