# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20161128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='название подборки')),
            ],
            options={
                'verbose_name': 'Подборка вин',
                'verbose_name_plural': 'Подборка вин',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='group',
            field=models.IntegerField(default=0, verbose_name='индикатор подборки'),
        ),
    ]
