# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_auto_20161128_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='название подборки')),
            ],
            options={
                'verbose_name_plural': 'Подборка вина',
                'verbose_name': 'Подборка вина',
            },
        ),
        migrations.AddField(
            model_name='wine',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Group', verbose_name='подборка вина'),
        ),
    ]
