# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_sorttowine'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='wine_to_sort',
            field=models.ManyToManyField(through='survey.SortToWine', to='survey.Sort'),
        ),
    ]
