# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_wine_wine_to_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='region',
            field=models.CharField(max_length=255, null=True, verbose_name='регион'),
        ),
    ]
