# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-05 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0024_wine_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.Wine', verbose_name='Вино')),
            ],
            options={
                'verbose_name_plural': 'Рекрмендованное',
                'verbose_name': 'Рекомендованное',
            },
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='api_response',
            new_name='api_answer_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='api_node',
            field=models.CharField(default='color', max_length=255, verbose_name='Node'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(default='/test/', upload_to='', verbose_name='Image for answer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('api_node', 'api_answer_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='recommended',
            unique_together=set([('user', 'wine')]),
        ),
    ]
